import React, { useState, useEffect } from 'react';
import axios from 'axios';

const Briefs = () => {
    const [briefs, setBriefs] = useState([]);

    useEffect(() => {
        const fetchData = async () => {
            try {
                const res = await axios.get(`${import.meta.env.VITE_API_URL || 'http://localhost:8000'}/api/content/briefs`);
                setBriefs(res.data);
            } catch (err) {
                console.error('Failed to fetch briefs', err);
            }
        };
        fetchData();
        const interval = setInterval(fetchData, 10000);
        return () => clearInterval(interval);
    }, []);

    return (
        <div className="card">
            <h2 style={{ marginBottom: '1rem', fontSize: '1.25rem' }}>All Content Briefs</h2>
            <p style={{ color: 'var(--text-secondary)', marginBottom: '1.5rem' }}>Generated by Agent 01 Content Strategist.</p>

            <div className="table-container">
                <table>
                    <thead>
                        <tr>
                            <th>Title</th>
                            <th>Keyword</th>
                            <th>Status</th>
                            <th>Created At</th>
                        </tr>
                    </thead>
                    <tbody>
                        {briefs.map((b, i) => (
                            <tr key={b.id || i}>
                                <td style={{ fontWeight: 500 }}>{b.title}</td>
                                <td style={{ color: 'var(--text-secondary)' }}>{b.target_keyword}</td>
                                <td>
                                    <span className={`badge ${b.status.toLowerCase()}`}>{b.status}</span>
                                </td>
                                <td style={{ color: 'var(--text-secondary)' }}>{new Date(b.created_at).toLocaleString()}</td>
                            </tr>
                        ))}
                        {briefs.length === 0 && (
                            <tr>
                                <td colSpan="4" style={{ textAlign: 'center', color: 'var(--text-secondary)' }}>No briefs found.</td>
                            </tr>
                        )}
                    </tbody>
                </table>
            </div>
        </div>
    );
};
export default Briefs;
